#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
            }
        }
    }
}
namespace Chess {
    ref class BoardSpace;
    ref class BoardOutline;
}

namespace Chess
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class Game : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
    
        private: ::Windows::UI::Xaml::Controls::Grid^ grdMainGrid;
        private: ::Chess::BoardSpace^ BoardSpace11;
        private: ::Chess::BoardSpace^ BoardSpace12;
        private: ::Chess::BoardSpace^ BoardSpace13;
        private: ::Chess::BoardSpace^ BoardSpace14;
        private: ::Chess::BoardSpace^ BoardSpace15;
        private: ::Chess::BoardSpace^ BoardSpace16;
        private: ::Chess::BoardSpace^ BoardSpace17;
        private: ::Chess::BoardSpace^ BoardSpace18;
        private: ::Chess::BoardSpace^ BoardSpace21;
        private: ::Chess::BoardSpace^ BoardSpace22;
        private: ::Chess::BoardSpace^ BoardSpace23;
        private: ::Chess::BoardSpace^ BoardSpace24;
        private: ::Chess::BoardSpace^ BoardSpace25;
        private: ::Chess::BoardSpace^ BoardSpace26;
        private: ::Chess::BoardSpace^ BoardSpace27;
        private: ::Chess::BoardSpace^ BoardSpace28;
        private: ::Chess::BoardSpace^ BoardSpace31;
        private: ::Chess::BoardSpace^ BoardSpace32;
        private: ::Chess::BoardSpace^ BoardSpace33;
        private: ::Chess::BoardSpace^ BoardSpace34;
        private: ::Chess::BoardSpace^ BoardSpace35;
        private: ::Chess::BoardSpace^ BoardSpace36;
        private: ::Chess::BoardSpace^ BoardSpace37;
        private: ::Chess::BoardSpace^ BoardSpace38;
        private: ::Chess::BoardSpace^ BoardSpace41;
        private: ::Chess::BoardSpace^ BoardSpace42;
        private: ::Chess::BoardSpace^ BoardSpace43;
        private: ::Chess::BoardSpace^ BoardSpace44;
        private: ::Chess::BoardSpace^ BoardSpace45;
        private: ::Chess::BoardSpace^ BoardSpace46;
        private: ::Chess::BoardSpace^ BoardSpace47;
        private: ::Chess::BoardSpace^ BoardSpace48;
        private: ::Chess::BoardSpace^ BoardSpace51;
        private: ::Chess::BoardSpace^ BoardSpace52;
        private: ::Chess::BoardSpace^ BoardSpace53;
        private: ::Chess::BoardSpace^ BoardSpace54;
        private: ::Chess::BoardSpace^ BoardSpace55;
        private: ::Chess::BoardSpace^ BoardSpace56;
        private: ::Chess::BoardSpace^ BoardSpace57;
        private: ::Chess::BoardSpace^ BoardSpace58;
        private: ::Chess::BoardSpace^ BoardSpace61;
        private: ::Chess::BoardSpace^ BoardSpace62;
        private: ::Chess::BoardSpace^ BoardSpace63;
        private: ::Chess::BoardSpace^ BoardSpace64;
        private: ::Chess::BoardSpace^ BoardSpace65;
        private: ::Chess::BoardSpace^ BoardSpace66;
        private: ::Chess::BoardSpace^ BoardSpace67;
        private: ::Chess::BoardSpace^ BoardSpace68;
        private: ::Chess::BoardSpace^ BoardSpace71;
        private: ::Chess::BoardSpace^ BoardSpace72;
        private: ::Chess::BoardSpace^ BoardSpace73;
        private: ::Chess::BoardSpace^ BoardSpace74;
        private: ::Chess::BoardSpace^ BoardSpace75;
        private: ::Chess::BoardSpace^ BoardSpace76;
        private: ::Chess::BoardSpace^ BoardSpace77;
        private: ::Chess::BoardSpace^ BoardSpace78;
        private: ::Chess::BoardSpace^ BoardSpace81;
        private: ::Chess::BoardSpace^ BoardSpace82;
        private: ::Chess::BoardSpace^ BoardSpace83;
        private: ::Chess::BoardSpace^ BoardSpace84;
        private: ::Chess::BoardSpace^ BoardSpace85;
        private: ::Chess::BoardSpace^ BoardSpace86;
        private: ::Chess::BoardSpace^ BoardSpace87;
        private: ::Chess::BoardSpace^ BoardSpace88;
        private: ::Chess::BoardOutline^ BoardOutline11;
        private: ::Chess::BoardOutline^ BoardOutline12;
        private: ::Chess::BoardOutline^ BoardOutline13;
        private: ::Chess::BoardOutline^ BoardOutline14;
        private: ::Chess::BoardOutline^ BoardOutline15;
        private: ::Chess::BoardOutline^ BoardOutline16;
        private: ::Chess::BoardOutline^ BoardOutline17;
        private: ::Chess::BoardOutline^ BoardOutline18;
        private: ::Chess::BoardOutline^ BoardOutline21;
        private: ::Chess::BoardOutline^ BoardOutline22;
        private: ::Chess::BoardOutline^ BoardOutline23;
        private: ::Chess::BoardOutline^ BoardOutline24;
        private: ::Chess::BoardOutline^ BoardOutline25;
        private: ::Chess::BoardOutline^ BoardOutline26;
        private: ::Chess::BoardOutline^ BoardOutline27;
        private: ::Chess::BoardOutline^ BoardOutline28;
        private: ::Chess::BoardOutline^ BoardOutline31;
        private: ::Chess::BoardOutline^ BoardOutline32;
        private: ::Chess::BoardOutline^ BoardOutline33;
        private: ::Chess::BoardOutline^ BoardOutline34;
        private: ::Chess::BoardOutline^ BoardOutline35;
        private: ::Chess::BoardOutline^ BoardOutline36;
        private: ::Chess::BoardOutline^ BoardOutline37;
        private: ::Chess::BoardOutline^ BoardOutline38;
        private: ::Chess::BoardOutline^ BoardOutline41;
        private: ::Chess::BoardOutline^ BoardOutline42;
        private: ::Chess::BoardOutline^ BoardOutline43;
        private: ::Chess::BoardOutline^ BoardOutline44;
        private: ::Chess::BoardOutline^ BoardOutline45;
        private: ::Chess::BoardOutline^ BoardOutline46;
        private: ::Chess::BoardOutline^ BoardOutline47;
        private: ::Chess::BoardOutline^ BoardOutline48;
        private: ::Chess::BoardOutline^ BoardOutline51;
        private: ::Chess::BoardOutline^ BoardOutline52;
        private: ::Chess::BoardOutline^ BoardOutline53;
        private: ::Chess::BoardOutline^ BoardOutline54;
        private: ::Chess::BoardOutline^ BoardOutline55;
        private: ::Chess::BoardOutline^ BoardOutline56;
        private: ::Chess::BoardOutline^ BoardOutline57;
        private: ::Chess::BoardOutline^ BoardOutline58;
        private: ::Chess::BoardOutline^ BoardOutline61;
        private: ::Chess::BoardOutline^ BoardOutline62;
        private: ::Chess::BoardOutline^ BoardOutline63;
        private: ::Chess::BoardOutline^ BoardOutline64;
        private: ::Chess::BoardOutline^ BoardOutline65;
        private: ::Chess::BoardOutline^ BoardOutline66;
        private: ::Chess::BoardOutline^ BoardOutline67;
        private: ::Chess::BoardOutline^ BoardOutline68;
        private: ::Chess::BoardOutline^ BoardOutline71;
        private: ::Chess::BoardOutline^ BoardOutline72;
        private: ::Chess::BoardOutline^ BoardOutline73;
        private: ::Chess::BoardOutline^ BoardOutline74;
        private: ::Chess::BoardOutline^ BoardOutline75;
        private: ::Chess::BoardOutline^ BoardOutline76;
        private: ::Chess::BoardOutline^ BoardOutline77;
        private: ::Chess::BoardOutline^ BoardOutline78;
        private: ::Chess::BoardOutline^ BoardOutline81;
        private: ::Chess::BoardOutline^ BoardOutline82;
        private: ::Chess::BoardOutline^ BoardOutline83;
        private: ::Chess::BoardOutline^ BoardOutline84;
        private: ::Chess::BoardOutline^ BoardOutline85;
        private: ::Chess::BoardOutline^ BoardOutline86;
        private: ::Chess::BoardOutline^ BoardOutline87;
        private: ::Chess::BoardOutline^ BoardOutline88;
    };
}

