#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class Button;
                ref class TextBlock;
                ref class ComboBox;
                ref class TextBox;
            }
        }
    }
}

namespace Chess
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class Start : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
    
        private: ::Windows::UI::Xaml::Controls::Grid^ grmMain;
        private: ::Windows::UI::Xaml::Controls::Button^ btnStart;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ lblTitle;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ lblSubTitleOne;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ lblSubTitleTwo;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ lblDesc11;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ cboType1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ lblDesc12;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ cboType2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ lblDesc21;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ cboDiff1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ lblDesc22;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ cboDiff2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ lblDesc31;
        private: ::Windows::UI::Xaml::Controls::TextBox^ txtName1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ lblDesc32;
        private: ::Windows::UI::Xaml::Controls::TextBox^ txtName2;
    };
}

